[pytest]
markers =
;    sanity: To ensure that new changes haven't introduced any defects or broken existing functionalities in the SW
;    regression: To verify that newly added or modified features work as expected after minor changes or bug fixes
;    functional: To verify core flows
;    api: To cover the API layer
addopts = --html=reports/report.html
testpaths = tests